import Link from "next/link";
import "./globals.css";
import Image from "next/image";

import Phone from '@/icons/phone.svg';
import WhatsApp from '@/icons/whatsapp.svg';
import Calendar from '@/icons/calendar.svg';

export const metadata = {
  title: "Maven",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Gideon+Roman&family=Hurricane&family=Raleway:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className="min-h-screen flex flex-col font-raleway">
        {/* Right Side Floating Panel */}
        <div className="fixed right-0 top-1/2 -translate-y-1/2 z-20 bg-darkpurple rounded-tl-2xl rounded-bl-2xl overflow-hidden">
          <div className="hidden md:flex flex-col gap-4 text-white px-3 py-3">
            <Link href={'#'} className="border-b border-golden flex flex-col items-center gap-2 ">
              <Image src={Phone} alt="Phone Icon" className=" w-7 h-7" />
              <span className="text-xs text-golden pb-3">Call Now</span>
            </Link>

            <Link href={'#'} className="border-b border-golden flex flex-col items-center gap-2">
              <Image src={WhatsApp} alt="WhatsApp Icon" className=" w-7 h-7" />
              <span className="text-xs text-golden pb-3">WhatsApp</span>
            </Link>

            <Link href={'#'} className="flex flex-col border-golden items-center gap-2">
              <Image src={Calendar} alt="Calendar Icon" className=" w-7 h-7" />
              <span className="text-xs text-golden pb-3">Book Now</span>
            </Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}