import "./globals.css";
import ClientProviders from "./components/clientproviders";
import FloatingPanel from "./components/floatingpanel";

export const metadata = {
  title: "Maven",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Gideon+Roman&family=Hurricane&family=Raleway:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className="min-h-screen flex flex-col font-raleway overflow-x-hidden">
        <ClientProviders>
          <FloatingPanel />
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}